### ISSUE TITLE
XY Pad Question

### ISSUE THREAD

**Issue by mew0717** [Sian-Lee-SA/honeycomb-menu#10]
Amazing service.. great flexibility.  I'm trying to get the XY_pad to work. but having some difficulties. 
I've installed via HACS and am running in Lovelace Storage mode (not yaml mode).  are the x, y, x_percentage and y_percentage variable supported by default?  I get buttons working no problem, but not having any luck with xy_pad.

```
 entity: light.downstairs_hallway_main_lights
          xy_pad:
            repeat: 500
            'y':
               invert: true
               service: light.turn_on
               service_data:
                 entity_id: light.downstairs_hallway_main_lights
                 brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
```
