### ISSUE TITLE
are browser_mod services and light-popup card supported?

### ISSUE THREAD

**Issue by mew0717** [Sian-Lee-SA/honeycomb-menu#13]
https://github.com/thomasloven/hass-browser_mod
https://github.com/DBuit/light-popup-card

BTW -- if i haven't said it recently, i freakin' love this module. Youtube content is killer too!  I'm trying to get a light-popup card to render with a click action off of one of the buttons in the honeycomb.   Normal tap-actions (toggle, more-info etc) all work fine.

here's the code with the honeycomb (i tried to copy your blue outline and im butchering it.. so looking forward to that vid as well)

```
  - type: image
      entity: light.master_bathroom_lights
      image: /local/Floorplan/transparent.png
      tap_action:
        action: toggle
      style:
        border: 4px solid cyan
        width: 230px
        height: 175px
        top: 17.5%
        left: 58%
        opacity: '${states[''light.master_bathroom_lights''].state === ''on'' ? ''.5'' : ''0'' }'
      hold_action:
        action: call-service
        service: honeycomb
        service_data:
          buttons:
            - icon: 'mdi:fan'
              entity: light.master_bathroom_exhaust_fan
              state:
                - value: 'on'
                  spin: true
              tap_action:
                action: toggle
              styles:
                icon:
                  - color: white
            - icon: 'mdi:lightbulb'
              entity: light.master_bathroom_lights
              state:
                - value: 'on'
                  color: yellow
                - value: 'off'
                  color: white
              tap_action:
                action: fire-dom-event
                browser_mod:
                  command: popup
                  card:
                    type: 'custom:light-popup-card'
                    entity: light.master_bathroom_lights
                    brightnessWidth: 150px
                    brightnessHeight: 400px
                    switchWidth: 150px
                    switchHeight: 400px
```

**Comment by Sian-Lee-SA** [comment]
I use browser_mod which seems to work fine, I have no experience with light-popup card but it should work fine as I can't imagine any conflicts... In regards to browser_mod, I do the following:

```
tap_action:
  action: service-call
  service: browser_mod.popup
  service_data:
    data_options_here...
```

Also thanks again for your support and compliments 😄
