### ISSUE TITLE
No Buttons in Honeycomb Menu

### ISSUE THREAD

**Issue by MrThiemann** [Sian-Lee-SA/honeycomb-menu#14]
Hey,

I don't know why, but no buttons are displayed.

I've been trying to integrate your honeycomb menu into my HA for days.
Unfortunately, only empty tiles are shown to me.
It is not possible for me to include any entities here.

<img width="453" alt="Bildschirmfoto 2021-08-13 um 08 08 52" src="https://user-images.githubusercontent.com/54147030/129312803-5d4ee7af-dab5-4d86-ace2-b9bd5be07d7d.png">

```   
- type: custom:vertical-stack-in-card
    style:
      top: 57%
      left: 35%
    title: My Card
    cards:
      - type: button
        entity: light.extended_color_light_2
        hold_action:
          action: call-service
          service: honeycomb
          service_data:
            template: light
            buttons:
              - show: '[[[ return (variables.motion) ]]]'
                entity: '[[[ return variables.motion ]]]'
                icon: mdi:lightbulb
                position: 4
                active: true
                tap_action:
                  action: toggle
              - show: '[[[ return (variables.timer) ]]]'
                entity: '[[[ return variables.timer ]]]'
                icon: mdi:lightbulb
                position: 5
                active: true
                tap_action:
                  action: toggle
```

Even if I use the standard code from the instructions, I only see empty tiles.

is it possible for me to get a working code? I would like to know where the problem is.
thank you from Germany

**Comment by Sian-Lee-SA** [comment]
do you have custom button-card installed?

**Comment by MrThiemann** [comment]
> do you have custom button-card installed?

yes,  I have.

**Comment by Sian-Lee-SA** [comment]
I just recently made some changes. There had been issues with the show option... just download the js file from the root of this repo and see how that goes. just rememberr to clear cache

**Comment by MrThiemann** [comment]
okay, i'm going to take a look. is there a sample code? that you can easily integrate (where you only have to change the entity) that works in any case?

**Comment by Sian-Lee-SA** [comment]
your code looks ok to me... but for simple testing purposes, remove template option and the show options thern just hard code the entity into the entity option...

**Comment by MrThiemann** [comment]
<img width="263" alt="Bildschirmfoto 2021-08-13 um 09 15 16" src="https://user-images.githubusercontent.com/54147030/129319319-c48cce3d-f31b-48cd-8773-f9920327a370.png">

i think we are on the right track! Thank you in advance for the quick support !!

**Comment by Sian-Lee-SA** [comment]
Ok i think you're just missing the variables that you're testing with. If you have a template light in a template file ( keep in mind that custom:button-card and honeycomb menu uses different template files )....

Looking at your code again... you've added a templates code into the action. templates uses the variables where the call-service would pass in the variables to the template.... if your unfamiliar with templating, then just stick without using templates and variables until youre comfortable in doing so

**Comment by MrThiemann** [comment]
Hey, could you maybe share a demo code of how you use it for your lamps?

**Comment by Sian-Lee-SA** [comment]
Sure!

```
hold_action:
  action: call-service
  service: honeycomb
  service_data:
    color: var(--paper-item-icon-color)
    xy_pad:
      repeat: 500
      y:
        invert: true
        service: light.turn_on
        service_data:
          entity_id: entity
          brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
    buttons:
      - icon: 'mdi:information-variant'
        tap_action:
          action: more-info
      - icon: 'mdi:lightbulb'
        active: true
      - entity: automation.bedroom_lamp_motion
        icon: 'mdi:motion-sensor'
        position: 4
        active: true
        tap_action:
          action: toggle
      - entity: automation.bedroom_lamp_timer
        icon: 'mdi:timer'
        position: 5
        active: true
        tap_action:
          action: toggle
```

**Comment by MrThiemann** [comment]
that brings me a little further! Thank you!

But can it be that the honeycomb only works for "custom: vertical-stack-in-card" & "custom: button-card"?

I would also like to use this for "state-icon". or is the point "buttons" wrong in my code?


```  - type: state-icon
    entity: light.extended_color_light_2
    style:
      top: 17%
      left: 35%
    tap_action:
      action: call-service
      service: honeycomb
      service-data:
        entitiy: light.extended_color_light_2
        color: var(--paper-item-icon-color)
        xy_pad:
          repeat: 500
          x:
            invert: true
            service: light.turn_on
            service_data:
              entity_id: entity
              hue: '[[[ return {{ y }} / 18 * {{ y_percentage }}; ]]]'
          'y':
            invert: true
            service: light.turn_on
            service_data:
              entity_id: entity
              brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
        buttons:
          - icon: mdi:information-variant
            tap_action:
              action: more-info
          - icon: mdi:lightbulb
            active: true
          - icon: mdi:motion-sensor
            position: 4
            active: true
            tap_action:
              action: toggle ```

**Comment by Sian-Lee-SA** [comment]
Check your write up!

Check my comments
```
- type: state-icon
    entity: light.extended_color_light_2   # This and the following parameters should be tabbed to the same line as above
    style:
      top: 17%
      left: 35%
    tap_action:
      action: call-service
      service: honeycomb
      service-data:    # This should be service_data
        entitiy: light.extended_color_light_2
        color: var(--paper-item-icon-color)
        xy_pad:
          repeat: 500
          x:
            invert: true
            service: light.turn_on
            service_data:
              entity_id: entity
              hue: '[[[ return {{ y }} / 18 * {{ y_percentage }}; ]]]'
          'y':
            invert: true
            service: light.turn_on
            service_data:
              entity_id: entity
              brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
        buttons:
          - icon: mdi:information-variant
            tap_action:
              action: more-info
          - icon: mdi:lightbulb
            active: true
          - icon: mdi:motion-sensor
            position: 4
            active: true
            tap_action:
              action: toggle 
```

**Comment by MrThiemann** [comment]
Great!! in germany we say: who can read has a clear advantage ^^

Just one thing:
I start my code with:

````
- type: state-icon
    entity: light.extended_color_light_2   # This and the following parameters should be tabbed to the same line as above
````

and when i adress the entites

````
      service_data:    #  :) :) :) :)
        entitiy: light.extended_color_light_2 # This should be entity
````
what should ideally be here?

````
entitiy: entity
````
or
```
entity_id: entity
`````
no matter what I enter there, the tiles open and I see the button, but they cannot be executed.

I've got everywhere there now "_entity: light.extended_color_light_2_" and it works!
I don't know now whether this has to be changed because it works. but that would interest me;)

````
    - type: state-icon
    entity: light.extended_color_light_2
    style:
      top: 77%
      left: 35%
    tap_action:
      action: toggle
    hold_action:
      action: call-service
      service: honeycomb
      service_data:
        entity: light.extended_color_light_2
        color: var(--paper-item-icon-color)
        xy_pad:
          repeat: 500
          x:
            invert: true
            service: light.turn_on
            service_data:
              entity: light.extended_color_light_2
              hue: '[[[ return {{ y }} / 18 * {{ y_percentage }}; ]]]'
          'y':
            invert: true
            service: light.turn_on
            service_data:
              entity: light.extended_color_light_2
              brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
        buttons:
          - icon: mdi:information-variant
            tap_action:
              action: more-info
          - icon: mdi:lightbulb
            active: true
          - icon: mdi:motion-sensor
            position: 4
            active: true
            tap_action:
              action: toggle
````
Thanks for your quick support!
