### ISSUE TITLE
different views in safari and chrome

### ISSUE THREAD

**Issue by MrThiemann** [Sian-Lee-SA/honeycomb-menu#15]
I just noticed that the Honeycomb menu works "differently" in the browsers.

the first picture is taken in the chrome
<img width="231" alt="Bildschirmfoto 2021-08-16 um 06 21 45" src="https://user-images.githubusercontent.com/54147030/129511161-ca4b53b0-e210-434b-a148-49b2b96a23d5.png">

the second picture is taken in the safari
<img width="237" alt="Bildschirmfoto 2021-08-16 um 06 22 57" src="https://user-images.githubusercontent.com/54147030/129511227-14be6dc9-af8d-4304-8bf6-baadd9f30640.png">

now i would say that the honeycomb does not work in safari. But:

this was done in safari:
<img width="327" alt="Bildschirmfoto 2021-08-16 um 06 24 32" src="https://user-images.githubusercontent.com/54147030/129511339-97d11dcc-7c4b-4150-b31d-bcb709b142b3.png">

the code for the menu in the safari are also "old" building blocks .... I can say that as soon as I add buttons to the tiles, the menu can no longer be opened

do you know if there are any disagreements here?

Code Chrome:
````
  - type: state-icon
    entity: light.extended_color_light_3_flur_eg
    style:
      top: 77%
      left: 50%
    tap_action:
      action: toggle
    hold_action:
      action: call-service
      service: honeycomb
      service_data:
        entity: light.extended_color_light_3_flur_eg
        color: var(--paper-item-icon-color)
        xy_pad:
          repeat: 500
          x:
            invert: true
            service: light.turn_on
            service_data:
              entity: light.extended_color_light_3_flur_eg
              hue: '[[[ return {{ y }} / 18 * {{ y_percentage }}; ]]]'
          'y':
            invert: true
            service: light.turn_off
            service_data:
              entity: light.extended_color_light_3_flur_eg
              brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'
        buttons:
          - icon: mdi:information-variant
            tap_action:
              action: more-info
          - icon: mdi:lightbulb
            active: true
          - icon: mdi:motion-sensor
            position: 4
            active: true
            tap_action:
              action: toggle
````

code safarie:
````
 - type: state-icon
    entity: light.extended_color_light_3_flur_eg
    style:
      top: 66%
      left: 25%
    tap_action:
      action: toggle
    hold_action:
      action: call-service
      service: honeycomb
      service_data: null ##I'm not sure whether "null" can be used here? is added there automatically
      entity: light.extended_color_light_3_flur_eg
      buttons:
        - icon: mdi:information_variant
          tap_action:
            action: more-info
        - icon: mdi:fan-speed-1
          tap_action:
            action: call-service
````
