### ISSUE TITLE
Cannot read property of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by Royrdan** [Sian-Lee-SA/honeycomb-menu#17]
Hi thanks for awsome module! This is exactly what I need but I cannot get it working.
I have the below basic code that Im using just to test before I code my whole floorplan.
When I hold the item i do get a dimmed screen with nothing else but the error.
Then when selecting anywhere on the screen it un-dimms and throws the other error.
I have added the module but I am getting the errors:
webpack:///./src/honeycomb-menu.js?:350:67 Uncaught TypeError: Cannot read properties of undefined (reading 'addEventListener')
and
https://<HOMEASSISTANT-URL>.ui.nabu.casa/frontend_latest/app.f08a72d3.js:849:77999 Uncaught TypeError: Cannot read properties of null (reading 'adoptedStyleSheets')

```
...
- type: picture-elements
  elements:
    - type: image
      ...
      hold_action:
        action: call-service
        service: honeycomb
        service_data:
          buttons:
            - entity: light.kitchen
              icon: 'mdi:broom'
              tap_action:
                action: more-info
            - entity: light.kitchen_led
              icon: 'mdi:broom'
              tap_action:
                action: more-info
            - entity: light.laundry
              icon: 'mdi:broom'
              tap_action:
                action: more-info
```

Not sure if it is interfering with another module I might have installed?
I have these modules installed

- decluttering-card.js
- group-card.js
- kiosk-mode.js
- light-entity-card.js
- lovelace-card-templater.js
- lovelace-card-templater.js
- card-tools.js
- layout-card.js
- more-info-card.js
- mini-media-player-bundle.js
- search-card.js
- text-element.js
- card-tools.js
- honeycomb-menu.js
- now-playing-card.js
