### ISSUE TITLE
honeycomp logs errors when invoked

### ISSUE THREAD

**Issue by bernji** [Sian-Lee-SA/honeycomb-menu#22]
Hello there,

I want to use the module with a floor plan following your guide.
I have installed the honeycomp-menu and card-tools and configured honeycomp inside the rules section of the floorplan-card as follows:

```
        - entities:
          - switch.e5_s4_hwr_waschmaschine
          tap_action: toggle
          hold_action:
            action: call-service
            service: honeycomb
            service_data:
              active: true
              buttons:
                - entity: cover.e8_r1_wohnen_gross_fenster
                  icon: mdi:blinds
                  tap_action:
                    action: more-info
                - entity: cover.e8_r2_wohnen_klein_fenster
                  icon: mdi:blinds-open
                  tap_action:
                    action: more-info
                - entity: climate.e6_e7_e8_t1_kueswo_temperatur
                  icon: mdi:thermometer
                  tap_action:
                    action: more-info
```

when performing the hold action on the entity I can see the error in the logs:

```
typography.js:181 
        
       Uncaught TypeError: Cannot read properties of null (reading 'adoptedStyleSheets')
    at HoneycombMenuItem._createLovelaceCard (honeycomb-menu-item.js:169:67)
    at HoneycombMenuItem.ready (honeycomb-menu-item.js:136:34)
    at HoneycombMenuItem._enableProperties (typography.js:181:1)
    at a.__enableOrFlushClients (typography.js:181:1)
    at a._readyClients (typography.js:181:1)
    at a._flushClients (typography.js:181:1)
    at a._propertiesChanged (typography.js:181:1)
    at a._flushProperties (typography.js:181:1)
    at a.ready (typography.js:181:1)
    at a._enableProperties (typography.js:181:1)
```

Is this a bug or what am I doing wrong? Do I need a specific version of card-tools (I used the latest) so maybe there are some incompatibilities?
