### ISSUE TITLE
Menu does not popup

### ISSUE THREAD

**Issue by Maxcodesthings** [Sian-Lee-SA/honeycomb-menu#27]
Following the Readme I cannot seem to get the menu to popup
```
- type: button
  entity: fan.fabian
  hold_action:
    action: call-service
    service: honeycomb
    service_data:
      template: light
      autoclose: false
      active: true
      buttons:
        - icon: mdi:fan-auto
          tap_action:
          action: call-service
          service: fan.set_preset_mode
          service_data:
            preset_mode: auto
            entity_id: fan.fabian
```
I have checked the sources in chrome developer tools and honeycomb-menu.js is listed so I believe its loaded properly.
Nothing happens when holding over the button, nor if I change to `tap_action`
