### ISSUE TITLE
honeycomb menu does not appear with template switch entities

### ISSUE THREAD

**Issue by duceduc** [Sian-Lee-SA/honeycomb-menu#28]
I am testing out the honeycomb menu and have noticed not all entities are compatible? I am able to see the blank dark honeycomb menu after installing the .js file. However, if I input the below entity which is a template switch, the honeycomb menu does not appear. If I use a different entity ( a switch entity via a broadlink IR command), the menu shows up. I have tried other template switch and the menu does not show up as well. Below is a snipet of the code I am testing with.

        - entity: switch.jcom_tv
          tap_action:
            action: 'toggle'
          hold_action:
            action: call-service
            service: honeycomb
            service_data:
              autoclose: false
              active: true
              buttons:
                - icon: mdi:information-variant
                  color_type: card
                  color: rgb(135,206,250, .7)
                  styles:
                    icon:
                      - width: 40%
                - icon: mdi:monitor
                - icon: mdi:volume-minus
                - icon: mdi:volume-mute
                - icon: mdi:monitor-lock
                  color_type: card
                  color: rgb(135,206,250, .7)
                  styles:
                    icon:
                      - width: 40%
                - icon: mdi:volume-plus
                  color_type: card
                  color: rgb(135,206,250, .7)
                  styles:
                    icon:
                      - width: 40%

**Comment by Sian-Lee-SA** [comment]
Is there anything in the console log to help debug? I have not ran into this issue but curious as to why it would happen as I can't think of a logical reason for doing so.

**Comment by duceduc** [comment]
Hey there. I figured it out. User error. I didn't change the entity in inkscape

On another note. The style icon above is what I want for all the honeycomb color and width size to be. However, I did not want to add the style every time. I think we can do this with a template, but  am lost as how to create the template and call it afterwards.

**Comment by Sian-Lee-SA** [comment]
For color theming I would suggest defining the honeycomb colors in your theme file... Check https://www.youtube.com/watch?v=xF4f2JJO9AI and the chapter Honeycomb Menu to get an idea about this... I will probably do a video soon in regards to using templates for the honeycomb menu. For now, just add the template in your config for your dashboard like described in the readme then add the same name of the template to the service_data

**Comment by Sian-Lee-SA** [comment]
for example, in your dashboard config.yaml do
```yaml

honeycomb_menu_templates:
  base:
    color: var(--paper-item-icon-color)
    audio: /local/audio/pin-drop.ogg
    styles:
      icon:
        - filter: "drop-shadow(rgba(255, 255, 255, 0.5) 1px 1px 0px)"
 ```

You can also add more templates or even child a template from another...

in your honeycomb menu call, just do the following

```yaml
      hold_action:
        action: call-service
        service: honeycomb
        service_data:
          template: base
          buttons:
            - icon: 'mdi:information-variant'
              tap_action:
                action: more-info
            - entity: automation.notify_kitchen_cupboard_opened
              active: true
              tap_action:
                action: toggle
            - icon: 'mdi:timeline'
              tap_action:
                  action: fire-dom-event
                  browser_mod: !include
                    - ../dashboards/primary/dialogs/timeline.yaml
                    - entities:
                      - binary_sensor.kitchen_cupboard_latch_contact
```

Notice the template parameter as thats the important one... This is just a copy from my own config so change to suit your needs
