### ISSUE TITLE
Fail to call any xxx.toggle from the ui

### ISSUE THREAD

**Issue by bernardovalente** [Sian-Lee-SA/honeycomb-menu#34]
hello!

HA can't call seem to call any xxx.toggle services from the ui, only from the developer tools. Only resolved if I uninstall honeycomb
![error](https://user-images.githubusercontent.com/15112071/210096928-83bf181e-6e83-4d3e-8e6d-2187dbcedec8.png)

works on developer tools:
```
service: light.toggle
data: {}
target:
  entity_id: light.leds_laura
```

doesn't work on ui generated button:
```
type: button
tap_action:
  action: call-service
  service: light.toggle
  data: {}
  target:
    entity_id: light.leds_laura
```

**Comment by karwosts** [comment]
Two more reports of same issue: 

https://discordapp.com/channels/330944238910963714/672220541343760384/1058433888092962876

https://github.com/home-assistant/frontend/issues/10550

**Comment by Sian-Lee-SA** [comment]
Thanks for bringing this to my attention, been unware of this but hadn't been updated (oversight). Could you try the latest realease? I also don't use discord so posting there won't get to me.

**Comment by bernardovalente** [comment]
Installed the latest release and I can now do service toggle calls using buttons in the UI but the issue still remains if using the honeycomb service:

```
type: button
entity: light.leds_laura
show_name: false
show_icon: true
show_state: false
icon_height: 50px
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    autoclose: true
    active: true
    buttons:
      - icon: mdi:looks
        active: true
        show_name: false
        tap_action:
          action: call-service
          service: light.toggle
          data:
            effect: Rainbow Effect With Custom Values
          target:
            entity_id: light.leds_laura
```

**Comment by Sian-Lee-SA** [comment]
Try removing the target and putting entity_id into data... target was introduced in home assistant at a later stage but not adapted to js frontend

**Comment by Sian-Lee-SA** [comment]
I just checked my code to refresh (been a while) and realised the buttons and their actions are handled by custom:button_card so if target being in there is causing the issue then it's because custom button card hasn't updated to use targets for their service calls.

**Comment by bernardovalente** [comment]
I tried using a custom:button_card and indeed the same thing happens. Will report to them as well

**Comment by Sian-Lee-SA** [comment]
So is this just because of target being in the service call? Just curious as all my service calls are still working fine without target also can close this

**Comment by bernardovalente** [comment]
Care to show an example of how to call them without the target? Kinda new to HA

**Comment by Sian-Lee-SA** [comment]
Oh ok I thought that might be the case, prior to the introduction of target, entity_id's were just added to the data instead which is still compliant. So change
```yaml
        tap_action:
          action: call-service
          service: light.toggle
          data:
            effect: Rainbow Effect With Custom Values
          target:
            entity_id: light.leds_laura
```

to

```yaml
        tap_action:
          action: call-service
          service: light.toggle
          data:
            effect: Rainbow Effect With Custom Values
            entity_id: light.leds_laura
```

**Comment by Sian-Lee-SA** [comment]
I also think data needs to be called `service_data`... I think you're copying straight from the developer tools which is generally different to how other cards implement things...

So try
```yaml
        tap_action:
          action: call-service
          service: light.toggle
          service_data:
            effect: Rainbow Effect With Custom Values
            entity_id: light.leds_laura

```
