### ISSUE TITLE
DOM Error when clicking button

### ISSUE THREAD

**Issue by RogerSelwyn** [Sian-Lee-SA/honeycomb-menu#37]
Just wanted to say thanks for all your work and tutorials on the HA Floorplan. Impressive stuff.

I've implemented a Honeycomb menu with a template as follows:

```yaml
- element: path_living_room
  hold_action:
     action: call-service
     service: honeycomb
     service_data:
      template: area
      autoclose: false
      variables:
         climate: climate.living_room
         light: light.living_room
         motion: binary_sensor.living_room_occupancy
```
```yaml
area:
  variables:
    light: null
    climate: null
    motion: null
  size: 150
  buttons:
    - icon: 'mdi:information-variant'
      entity: '[[[ return (variables.light) ]]]'
      tap_action:
         action: more-info
    - icon: 'mdi:lightbulb'
      entity: '[[[ return (variables.light) ]]]'
      active: true
      tap_action:
         action: turn_off
    - icon: 'mdi:motion-sensor'
      entity: '[[[ return (variables.motion) ]]]'
      active: true
      tap_action:
         action: more-info
    - icon: 'mdi:radiator'
      entity: '[[[ return (variables.climate) ]]]'
      active: true
      position: 5
      tap_action:
         action: more-info
```
I'm getting this error in the console when a clock a button. The button seems to work fine, just seems odd that I get an error

`downstairs:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

If it matters 'path_living_room' is not an entity. Also my lovelace config is broken up via includes, but I don't think that should make a difference. Whilst I maintain several integrations, so pretty good at the background stuff, I'm not sure how to debug the frontend.

**Comment by Sian-Lee-SA** [comment]
Thanks, I'll have a look into it when I get time and try to reproduce the issue. Probably just needs a error block for the promise which might end up being nothing. Because it's a DOMException, it's possibly a browser specific error.

**Comment by Sian-Lee-SA** [comment]
So I just did a play around and have a similar setup for my areas but I can't seem to reproduce the exception. Are all your variables  always defined?  If not use `show: '[[[ return (variables.light) ]]]` or climate etc.

**Comment by RogerSelwyn** [comment]
The `downstairs:1` shows as hyperlinked (and displays to the right of the error), but seems to go no where. I'm on Chrome 109.0.5414.87 (Official Build) (arm64) (MacBook Pro M1) if that matters.

I've simplified my template to try to remove the error, and then work from there. No joy, always the same error. I've also used entities that are not mentioned elsewhere in my config, just in case of conflict

```yaml
- elements: 
  - room_utility
  entity: light.bedside_light
  double_tap_action:
     action: call-service
     service: honeycomb
     service_data:
      template: area
```

```yaml
honeycomb_menu_templates: 
    area:
      size: 150
      buttons:
        - icon: 'mdi:information-variant'
          entity: light.bedside_light
          tap_action:
             action: more-info
```

I've also tried cutting this back to remove the template, still no change

```yaml
- elements: 
  - room_utility
  entity: light.bedside_light
  double_tap_action:
    action: call-service
    service: honeycomb
    service_data:
      size: 150
      buttons:
        - icon: 'mdi:information-variant'
          entity: light.bedside_light
          tap_action:
             action: more-info
```

That said, I see this doesn't work on iOS, so whilst I love the look and feel, I'm going to have to find another way to display the relevant content. I'm happy to continue to help debug if you wish.
