### ISSUE TITLE
Required key not provided @ data['service']. Got None

### ISSUE THREAD

**Issue by Fr3di** [Sian-Lee-SA/honeycomb-menu#46]
Home Assistant 2023.4.5 Docker
Honeycomb Menu 0.12.2 installed through HACS

Chrome 112 throws:
Failed to call service honeycomb/undefined. required key not provided @ data['service']. Got None

After looking at the console it shows below error:
```
{
    "code": "invalid_format",
    "message": "required key not provided @ data['service']. Got None"
}
```
Any idea how to fix it?

**Comment by Fr3di** [comment]
After investigation seems like when you use
```
tap_action:
```
you have to implement all possible options.

After changing this:
```
tap_action:
    action: more-info
```
to this:
```
tap_action:
    action: more-info
    tap_action: none
    hold_action: none
    double_tap_action: none
```
everything works fine 😄
