### ISSUE TITLE
honeycomb-menu in conjunction with 'browser_mod.popup'

### ISSUE THREAD

**Issue by pqpxo** [Sian-Lee-SA/honeycomb-menu#47]
Hi there,

I've noticed an issue when attempting to use a 'honeycomb-menu' element/config within a 'browser_mod.popup' configuration. 

When the 'honeycomb-menu' is called (action: call-service) via a 'tap_action' it is only visible behind the 'browser_mod.popup' card.

Code and screenshot attached ...

[Screenshot](https://imgur.com/Lmq2IkO)

```
service: browser_mod.popup
data:
  style: |
    --popup-min-width: 450px;
  dismissable: true
  content:
    type: vertical-stack
    cards:
      - type: custom:button-card
        color_type: blank-card
        styles:
          card:
            - height: 3px
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: Power
            icon: mdi:power
            tap_action:
              action: call-service
              service: honeycomb
              service_data:
                buttons:
                  - icon: mdi:volume-plus
                    color_type: card
                    color: green
                  - icon: mdi:volume-minus
                    color_type: card
                    color: green
                  - icon: mdi:volume-mute
                    color_type: card
                    color: green
                  - icon: mdi:television-classic
                    color_type: card
                    color: green
                  - icon: mdi:television-classic-off
                    color_type: card
                    color: green
                  - icon: mdi:play-pause
                    color_type: card
                    color: green
            show_icon: true
            styles:
              card:
                - height: 140px
              ...
```
