### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by FedgarLurch** [Sian-Lee-SA/honeycomb-menu#66]
Okay, so I like this module, I like the look of it (Haven't gotten into the floorplan thing yet, but that is next! 

I fully updated everything trying to solve this problem. I create the menus, and this is what I see:
Non Default theme, with some overrides:
![image](https://github.com/user-attachments/assets/845d45e2-1526-49ae-a256-e30556cf7691)
![image](https://github.com/user-attachments/assets/02f8548a-f38c-4d8a-b69e-3511bfaf61d1)

Default Theme:
![image](https://github.com/user-attachments/assets/9ee5ecf4-fe3f-4d54-b945-8cc6acf4f3a0)
![image](https://github.com/user-attachments/assets/f3528db8-7115-46a5-af4b-e14447254b73)

I am working with the default theme to elminate possible conflict. But I tried it with a few, and I tried it with a few different configurations of my yaml (Explicitly defining the CSS, explicitly defining the card type, auto, etc)

Weirdly it works fine when the light is on, but the background disapears when the light is off. Any ideas? Am I an idiot? 

Here is the yaml for the buttons:
Non Default w/ Overrides:
```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: light.kitchen
    hold_action:
      action: call-service
      service: honeycomb
      service_data:
        entity: light.kitchen
        buttons:
          - label: Kitchen Lights
            show_label: false
            tap_action:
              action: more-info
            icon: mdi:information
            color_type: card
            color: auto
          - label: Lights On
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: light.kitchen
            icon: mdi:lightbulb-outline
            color_type: card
            color: auto
          - label: Lights Off
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
            icon: mdi:lightbulb
            color_type: card
            color: auto
          - label: Lights 30%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 30
            icon: mdi:lightbulb-on-30
            color_type: card
            color: auto
          - label: Lights 70%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 70
            icon: mdi:lightbulb-on-70
            color_type: card
            color: auto
          - label: Lights 70%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 100
            icon: mdi:lightbulb-on
            color_type: card
            color: auto

```

Default:

```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: light.kitchen
    hold_action:
      action: call-service
      service: honeycomb
      service_data:
        entity: light.kitchen
        buttons:
          - label: Kitchen Lights
            show_label: false
            tap_action:
              action: more-info
            icon: mdi:information
            color_type: icon
          - label: Lights On
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
            icon: mdi:lightbulb-outline
            color_type: icon
          - label: Lights Off
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: light.kitchen
            icon: mdi:lightbulb
            color_type: icon
          - label: Lights 30%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 30
            icon: mdi:lightbulb-on-30
            color_type: icon
          - label: Lights 70%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 70
            icon: mdi:lightbulb-on-70
            color_type: icon
          - label: Lights 100%
            show_label: false
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen
                brightness_pct: 100
            icon: mdi:lightbulb-on
            color_type: icon
```

**Comment by Sian-Lee-SA** [comment]
You can define your styles for the honeycomb menu through your {theme}.yaml file https://github.com/Sian-Lee-SA/honeycomb-menu?tab=readme-ov-file#theme-styles-and-defaults. Alternatively you can customise each button by reading up on [button-card](https://github.com/custom-cards/button-card) and its options.

**Comment by FedgarLurch** [comment]
Thanks for getting back to me. 
I am pretty weak on my knowledge of themes. But really basically, I created a test.yaml theme and selected it with just what you have on your wiki:

```
Test:
  honeycomb-menu-icon-color: var(--paper-item-icon-color)
  honeycomb-menu-icon-active-color: var(--paper-item-icon-active-color)
  honeycomb-menu-background-color: var(--paper-card-background-color)
  honeycomb-menu-active-background-color: var(--paper-card-active-background-color, var(--paper-card-background-color))
  honeycomb-menu-disabled: "#9a9a9a6e"
```

But its still giving me some very strange results. That every other hex being colored / not colored is strange, since each button has the same configuration. 

I am sure your stuff works perfectly, I assume its somethign with my setup, I am just at a loss on how to fix it. Any help is appreciated.
