### ISSUE TITLE
Issue with YXpad (can't use "y" variable) in Honeycomb Menu

### ISSUE THREAD

**Issue by Scarpetta3** [Sian-Lee-SA/honeycomb-menu#69]
Hello,
I was able to use all the features of this spectacular menu that you develop, I missed just one thing.
I have tried a lot but it seems I can't figure out what I am missing.
I am tying to make xypad work for my cover but I receive an error.
I searched a lot in guides (for example this one: [Link](https://smarthomescene.com/guides/honeycomb-module-hex-popup-menu-for-home-assistant/) from which I substantially copy and paste the snippet of code for my service call on cover) and in your documentation but with no success.

This is my code for a nested Honeycomb Menu (if I put it on a non nested I have the same result):

```
tap_action:
  type: "custom:button-card"
  action: call-service
  service: honeycomb
  service_data:
    entity: cover.tapparella_camera_singola
    xy_pad:
      on_release: true
      y:
        # action: call-service
        service: cover.set_cover_position
        service_data:
          entity_id: cover.tapparella_camera_singola
          position: '{{  y }}'
```

The error I receive is the follow:

> Failed to perform the action cover/set_cover_position. expected int for dictionary value @ data['position']

For now what I want to reach is to have a number from that "y" variable. The next step will be to return "100" for positive values and "0" for negative ones.

Thank You very much in advance

Regards
Matteo
