### ISSUE TITLE
XYPad unable to access variables

### ISSUE THREAD

**Issue by hilburn** [Sian-Lee-SA/honeycomb-menu#72]
Playing around with the XYPad I've found that it seems unable to access the 'variables' defined in the honeycomb menu servicedata

Minimal reproducible code:
```yaml
action: call-service
service: honeycomb
service_data:
  variables: 
    temperature: 15
  xy_pad:
    x:
      service: notify.persistent_notification
      service_data:
        data:
          notification_id: "test"
        message: '[[[ return JSON.stringify(variables) ]]]'
```

Output:
![image](https://github.com/user-attachments/assets/1dca2200-fc0f-436c-82df-0142e2e44d3c)

The variables are being set as the buttons are able to access them normally, but I can't seem to get anything within the xy_pad key to return anything other than an empty object.
