### ISSUE TITLE
Menu triggered in nested fields in custom:button-card wrong popup

### ISSUE THREAD

**Issue by samuele2723** [Sian-Lee-SA/honeycomb-menu#73]
hello there, any chance to reopen the issue #61  ? I am having the same and it happens when you nest the card with the tap action within a button card, please see example having a mushroom action inside a button card.

if i have the mushroom card alone it works as intended, instead when i get inside the button card it "reminds" the last click i did elsewere for the first trigger of the honeycomb. When i click second time, works as intented

```
type: custom:button-card
tap_action:
  action: none
template: inset
custom_fields:
  card_1:
    card:
      type: custom:mushroom-template-card
      entity: light.secondo_piano
      icon: mdi:home-floor-2
      icon_color: none
      layout: vertical
      hold_action:
        action: none
      tap_action:
        action: call-service
        service: honeycomb
        service_data:
          autoclose: true
          size: 230
          xy_pad: false
          spacing: 2
          animation_speed: 50
```

https://github.com/user-attachments/assets/af092a47-c711-42c1-b75a-8e8e3e412d5b
