### ISSUE TITLE
0:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by p4klt0** [Sian-Lee-SA/honeycomb-menu#75]
First, congratulations on the excellent work with this module.

I wanted to ask you if it's something I'm doing wrong, or is it a problem with the module because when the popup is displayed, after having displayed the menu, I get an error in the development console.

I have tried a new docker instance of Home Assistant, with only HACS, button-card, Honeycomb and hass-virtual (to have some entitties to test) installed, in case there was some incompatibility, but the result is the same.

I have set up a panel, just with:

```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading: section
          - show_name: true
            show_icon: true
            type: button
            entity: light.virtual_light_1
            hold_action:
              action: call-service
              service: honeycomb
              service_data:
                entity: light.virtual_light_1
                buttons:
                  - icon: mdi:information-variant
                    tap_action:
                      action: more-info
                  - show: false
                  - show: false
                  - show: false
                  - show: false
                  - show: false
```

But as I mentioned, after the menu appears, when I press the more-info button, the popup appears but in the development console it appears:

![image](https://github.com/user-attachments/assets/728735d5-2e58-4ba5-9ee8-1bff0122ce21)

Si puedo hacer alguna prueba mas, no tengo problema pues he configurado una instancia solo para poder probar.

Saludos

**Comment by ngocjohn** [comment]
you have to use the correct settings for action by custom:button-card 
```
buttons:
  - icon: mdi:information-variant
    tap_action:
      action: more-info
      entity_id: entity
```

**Comment by p4klt0** [comment]
Still not working properly. More info popup is shown but with the same errors on dev console.

Now, the code for the card is:

```
show_name: true
show_icon: true
type: button
entity: light.virtual_light_1
hold_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: light.virtual_light_1
    buttons:
      - icon: mdi:information-variant
        tap_action:
          action: more-info
          entity_id: light.virtual_light_1
      - show: false
      - show: false
      - show: false
      - show: false
      - show: false

```

**Comment by ngocjohn** [comment]
@p4klt0 It is a problem with lovelace storage mode, in yaml mode this error is not present.

**Comment by p4klt0** [comment]
Error still present on yaml mode. Added to configuration.yaml:

```
lovelace:
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/honeycomb-menu/honeycomb-menu.js
      type: module
  mode: yaml
  dashboards:
    test-yaml:
      mode: yaml
      title: test
      icon: mdi:test-tube
      show_in_sidebar: true
      filename: configurations/dashboards/test.yaml
```

And test.yaml:

```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:button-card
            entity: light.virtual_light_1
            hold_action:
              action: call-service
              service: honeycomb
              service_data:
                entity: light.virtual_light_1
                buttons:
                  - icon: mdi:information-variant
                    tap_action:
                      action: more-info
                  - show: false
                  - show: false
                  - show: false
                  - show: false
                  - show: false
```

The honeycomb menu appears and works, but when button is clicked, the error is shown in the dev console
