### ISSUE TITLE
JS conflict with Custom Button Card

### ISSUE THREAD

**Issue by FedgarLurch** [Sian-Lee-SA/honeycomb-menu#76]
**Description:** The honeycomb service in Home Assistant does not properly handle dynamic templates for service data, specifically when calculating values like position for cover.set_cover_position.

**Steps to Reproduce:**

Create a custom:button-card with the following configuration:
```
yaml
Copy code
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "{{ (y_percentage / 5) | int }}"
```

**Expected Behavior:**

The position value should dynamically calculate from the y_percentage variable and pass the result as an integer to cover.set_cover_position.

**Actual Behavior:**

Adding | int resolves type errors (expected int for dictionary value @ data['position']), but the service does not execute or update the cover position.
Hardcoding the position value (e.g., position: 65) works as expected.
Dynamic templates appear to be ignored or improperly resolved.
Additional Notes:

cover.set_cover_position works when called directly from Developer Tools.
Tested the template in Developer Tools > Template Editor, and it resolves correctly.
The issue seems specific to how honeycomb handles dynamic templates within xy_pad.

**Versions Tried with results**

```
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "[[[ return {{ y_percentage }} / 10; ]]]"
```

```
button-card.js?hacstag=146194325412:434 Uncaught ButtonCardJSTemplateError: SyntaxError: Unexpected token '{' in 'return {{ y_percentage }} / 10;'
    at new Function (<anonymous>)
    at Ti._evalTemplate (button-card.js?hacstag=146194325412:434:2161)
    at Ti._getTemplateOrValue (button-card.js?hacstag=146194325412:434:2877)
    at button-card.js?hacstag=146194325412:559:2699
    at Array.forEach (<anonymous>)
    at l (button-card.js?hacstag=146194325412:559:2641)
    at button-card.js?hacstag=146194325412:559:2681
    at Array.forEach (<anonymous>)
    at l (button-card.js?hacstag=146194325412:559:2641)
    at button-card.js?hacstag=146194325412:559:2681
    
```

But using your exact example, this works:
```
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "[[[ return 50 / 10; ]]]"
```
Works as expected, no errors

**Environment:**

Home Assistant version: 2024.11.3 & 2024.12.3
I had the old version of this, but I upgraded after seeing you had dropped a new version. No change. 
Also, I have a fully updated button card that I was working with to just make sure there were no shenanigans.

**Comment by Sian-Lee-SA** [comment]
Because you're going about it wrong, Honeycomb menu does not parse jinja. Read [Templating](https://github.com/Sian-Lee-SA/honeycomb-menu?tab=readme-ov-file#templating) to understand the difference, specificially _**Uses {{ variable }} syntax**_ as it states it's a variable within curly braces.

**Comment by FedgarLurch** [comment]
I did read the examples, and tried the examples. I also read other closed issues relating and tried everything that was there. I wasn't able to make headway. 

I will update and re-open my issue with more information.

**Comment by Sian-Lee-SA** [comment]
Did you hard reset and refresh the dashboard after making changes? because that's still saying you have { at the start of the string

**Comment by FedgarLurch** [comment]
Gotcha, I tried those, here is what it gave me with each iteration:

I created a new card, on a different dashboard (plus hard refreshing, just to be sure)
```
show_name: false
show_icon: true
type: button
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "[[[ return {{ x_percentage }}; ]]]"
```
`{code: 'invalid_format', message: "expected int for dictionary value @ data['position']"}`

Is what I got. 
I put 65 in there and it worked fine.

**Comment by Sian-Lee-SA** [comment]
change `position: "[[[ return {{ x_percentage }}; ]]]"` to `position: "[[[ return Math.round( {{ x_percentage }} ); ]]]"` and if you still want to divide, change to `position: "[[[ return Math.round( {{ x_percentage }} / 10); ]]]"`. The percentage is from memory a float and still needs to be parsed.

**Comment by Sian-Lee-SA** [comment]
What i think might be happening is Custom Button Card is parsing it internally because their syntax is the same so it's being translated before honeycomb menu even gets it's hands on it. Honestly, that's just my theory as I've never encountered it nor had issue raised about it but might be because noone else is using custom button card for their menu.

**Comment by Sian-Lee-SA** [comment]
It's something that I would rewrite myself on a different syntax to use the JS features, it's not Custom Button Cards problem as they're the top layer to the hierarchy and shouldn't bend to the will of 3rd party sub routines/processes etc. This module can't intercept it before Custom Button Card because there's just no entry point before hand. So I do apologise for not noticing you're using custom button card and the processing conflict it may be causing but after this many years that the module has been available and not a single issue on the matter, it just never crossed my mind.

For now I can only suggest using alternative cards til I come up with a quick hack fix but wont be high priority.

**Comment by FedgarLurch** [comment]
Is there anything I can do to help? 

Just so you can see what I am trying to do, here is one card I use for my mobile dashboard. Its a bit... involved

```
cards:
  - type: button
    tap_action:
      action: call-service
      service: automation.trigger
      service_data: {}
      target:
        entity_id: automation.bedtime
    entity: automation.bedtime
    icon: mdi:sleep
    show_name: false
    show_state: false
    show_icon: true
  - show_name: false
    show_icon: true
    type: custom:button-card
    entity: input_boolean.leavingroutine
    icon: mdi:application-parentheses-outline
    show_state: false
    styles:
      icon:
        - color: |
            [[[ 
              if (
                states['input_boolean.roomba'].state === 'off' ||
                states['input_boolean.extended_away'].state === 'off' ||
                states['input_boolean.hvac'].state === 'off' ||
                states['input_boolean.heat'].state === 'off'
              ) {
                return 'var(--state-active-color)';
              }
              return 'var(--paper-item-icon-color)';
            ]]]
    tap_action:
      action: call-service
      service: honeycomb
      service_data:
        autoclose: false
        buttons:
          - label: Other
            show_label: false
            tap_action:
              action: more-info
            icon: mdi:information
          - label: Disable Roomba
            entity: input_boolean.roomba
            show_label: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              target:
                entity_id: input_boolean.roomba
            icon: mdi:robot-vacuum
            state:
              - value: "off"
                icon: mdi:robot-vacuum-off
          - label: Toggle Extended Away
            entity: input_boolean.extended_away
            show_label: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              target:
                entity_id: input_boolean.extended_away
            icon: mdi:shield-lock
            state:
              - value: "off"
                icon: mdi:shield-lock-open
          - label: Toggle HVAC
            entity: input_boolean.hvac
            show_label: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              target:
                entity_id: input_boolean.hvac
            icon: mdi:hvac
            state:
              - value: "off"
                icon: mdi:hvac-off
          - label: Toggle Heat
            entity: input_boolean.heat
            show_label: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              target:
                entity_id: input_boolean.heat
            icon: mdi:radiator
            state:
              - value: "off"
                icon: mdi:radiator-off
    hold_action:
      action: none
  - type: custom:button-card
    show_name: false
    show_icon: true
    icon: |
      [[[ 
        // List of all the cover entities
        const covers = [
          'cover.window_1_shade_cover',
          'cover.window_2_shade_cover',
          'cover.window_3_shade_cover',
          'cover.window_4_shade_cover',
          'cover.window_5_shade_cover'
        ];

        // Check if ANY cover is 'open'
        const anyOpen = covers.some(cover => states[cover]?.state === 'open');

        // Return mdi:curtains if ANY is open, otherwise mdi:curtains-closed
        return anyOpen ? 'mdi:curtains' : 'mdi:curtains-closed';
      ]]]
    show_state: false
    styles:
      icon:
        - color: |
            [[[ 
              // List of all the cover entities
              const covers = [
                'cover.window_1_shade_cover',
                'cover.window_2_shade_cover',
                'cover.window_3_shade_cover',
                'cover.window_4_shade_cover',
                'cover.window_5_shade_cover'
              ];

              // Check if ALL covers are 'closed'
              const allClosed = covers.every(cover => states[cover]?.state === 'closed');

              // Return active color only if ALL are closed
              return allClosed ? 'var(--state-active-color)' : 'var(--paper-item-icon-color)';
            ]]]
    tap_action:
      action: call-service
      service: honeycomb
      service_data:
        autoclose: false
        buttons:
          - label: Other
            show_label: false
            tap_action:
              action: more-info
            icon: mdi:information
          - label: Window Shade 1
            entity: cover.window_1_shade_cover
            icon: |
              [[[ 
                let position = states['cover.window_1_shade_cover'].attributes.current_position || 0;
                if (position < 5) {
                  return 'mdi:curtains-closed'; // Fully closed
                } else if (position > 95) {
                  return 'mdi:curtains'; // Fully open
                } else {
                  return 'mdi:curtains'; // Partially open
                }
              ]]]
            show_label: false
            styles:
              icon:
                - color: |
                    [[[ 
                      let position = states['cover.window_1_shade_cover'].attributes.current_position || 0;
                      if (position < 5) {
                        return 'var(--state-active-color)'; // Fully closed
                      } else if (position > 95) {
                        return 'var(--paper-item-icon-color)'; // Fully open
                      } else {
                        return 'purple'; // Partially open
                      }
                    ]]]
              custom_fields:
                secondary_icon:
                  - position: absolute
                  - top: 16%
                  - right: 0%
                  - width: 20px
                  - color: var(--primary-text-color)
            custom_fields:
              secondary_icon: |
                [[[
                  return `<ha-icon icon="mdi:numeric-1-circle"></ha-icon>`;
                ]]]
            tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_1_shade_cover
              data:
                position: 0
            double_tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_1_shade_cover
              data:
                position: 100
            hold_action:
              action: more-info
          - label: Window Shade 2
            entity: cover.window_2_shade_cover
            icon: |
              [[[ 
                let position = states['cover.window_2_shade_cover'].attributes.current_position || 0;
                if (position < 5) {
                  return 'mdi:curtains-closed'; // Fully closed
                } else if (position > 95) {
                  return 'mdi:curtains'; // Fully open
                } else {
                  return 'mdi:curtains'; // Partially open
                }
              ]]]
            show_label: false
            styles:
              icon:
                - color: |
                    [[[ 
                      let position = states['cover.window_2_shade_cover'].attributes.current_position || 0;
                      if (position < 5) {
                        return 'var(--state-active-color)'; // Fully closed
                      } else if (position > 95) {
                        return 'var(--paper-item-icon-color)'; // Fully open
                      } else {
                        return 'purple'; // Partially open
                      }
                    ]]]
              custom_fields:
                secondary_icon:
                  - position: absolute
                  - top: 16%
                  - right: 0%
                  - width: 20px
                  - color: var(--primary-text-color)
            custom_fields:
              secondary_icon: |
                [[[
                  return `<ha-icon icon="mdi:numeric-2-circle"></ha-icon>`;
                ]]]
            tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_2_shade_cover
              data:
                position: 0
            double_tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_2_shade_cover
              data:
                position: 100
            hold_action:
              action: more-info
          - label: Window Shade 3
            entity: cover.window_3_shade_cover
            icon: |
              [[[ 
                let position = states['cover.window_3_shade_cover'].attributes.current_position || 0;
                if (position < 5) {
                  return 'mdi:curtains-closed'; // Fully closed
                } else if (position > 95) {
                  return 'mdi:curtains'; // Fully open
                } else {
                  return 'mdi:curtains'; // Partially open
                }
              ]]]
            show_label: false
            styles:
              icon:
                - color: |
                    [[[ 
                      let position = states['cover.window_3_shade_cover'].attributes.current_position || 0;
                      if (position < 5) {
                        return 'var(--state-active-color)'; // Fully closed
                      } else if (position > 95) {
                        return 'var(--paper-item-icon-color)'; // Fully open
                      } else {
                        return 'purple'; // Partially open
                      }
                    ]]]
              custom_fields:
                secondary_icon:
                  - position: absolute
                  - top: 16%
                  - right: 0%
                  - width: 20px
                  - color: var(--primary-text-color)
            custom_fields:
              secondary_icon: |
                [[[
                  return `<ha-icon icon="mdi:numeric-3-circle"></ha-icon>`;
                ]]]
            tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_3_shade_cover
              data:
                position: 0
            double_tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_3_shade_cover
              data:
                position: 100
            hold_action:
              action: more-info
          - label: Window Shade 4
            entity: cover.window_4_shade_cover
            icon: |
              [[[ 
                let position = states['cover.window_4_shade_cover'].attributes.current_position || 0;
                if (position < 5) {
                  return 'mdi:curtains-closed'; // Fully closed
                } else if (position > 95) {
                  return 'mdi:curtains'; // Fully open
                } else {
                  return 'mdi:curtainsl'; // Partially open
                }
              ]]]
            show_label: false
            styles:
              icon:
                - color: |
                    [[[ 
                      let position = states['cover.window_4_shade_cover'].attributes.current_position || 0;
                      if (position < 5) {
                        return 'var(--state-active-color)'; // Fully closed
                      } else if (position > 95) {
                        return 'var(--paper-item-icon-color)'; // Fully open
                      } else {
                        return 'purple'; // Partially open
                      }
                    ]]]
              custom_fields:
                secondary_icon:
                  - position: absolute
                  - top: 16%
                  - right: 0%
                  - width: 20px
                  - color: var(--primary-text-color)
            custom_fields:
              secondary_icon: |
                [[[
                  return `<ha-icon icon="mdi:numeric-4-circle"></ha-icon>`;
                ]]]
            tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_4_shade_cover
              data:
                position: 0
            double_tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_4_shade_cover
              data:
                position: 100
            hold_action:
              action: more-info
          - label: Window Shade 5
            entity: cover.window_5_shade_cover
            icon: |
              [[[ 
                let position = states['cover.window_5_shade_cover'].attributes.current_position || 0;
                if (position < 5) {
                  return 'mdi:curtains-closed'; // Fully closed
                } else if (position > 95) {
                  return 'mdi:curtains'; // Fully open
                } else {
                  return 'mdi:curtains'; // Partially open
                }
              ]]]
            show_label: false
            styles:
              icon:
                - color: |
                    [[[ 
                      let position = states['cover.window_5_shade_cover'].attributes.current_position || 0;
                      if (position < 5) {
                        return 'var(--state-active-color)'; // Fully closed
                      } else if (position > 95) {
                        return 'var(--paper-item-icon-color)'; // Fully open
                      } else {
                        return 'purple'; // Partially open
                      }
                    ]]]
              custom_fields:
                secondary_icon:
                  - position: absolute
                  - top: 16%
                  - right: 0%
                  - width: 20px
                  - color: var(--primary-text-color)
            custom_fields:
              secondary_icon: |
                [[[
                  return `<ha-icon icon="mdi:numeric-5-circle"></ha-icon>`;
                ]]]
            tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_5_shade_cover
              data:
                position: 0
            double_tap_action:
              action: call-service
              service: cover.set_cover_position
              target:
                entity_id: cover.window_5_shade_cover
              data:
                position: 100
            hold_action:
              action: more-info
    hold_action:
      action: none
  - type: custom:button-card
    show_name: false
    show_icon: true
    name: Living Room TV
    icon: mdi:remote-tv
    entity: remote.livingroom
    show_state: false
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Living Room TV
          content:
            type: custom:layout-card
            style:
              width: 80vw
              height: 80vh
            layout_type: grid
            layout:
              grid-template-rows: auto
              grid-template-columns: 30% 30% 30%
              margin: 35px 0px 35px 38px
            cards:
              - type: custom:button-card
                color: maroon
                icon: mdi:power
                name: TV Power
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: power
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:home
                name: Home
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: home
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:backburger
                name: Menu
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: menu
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:gap-card
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                aspect_ratio: 1/1
                size: 75px
                icon: mdi:chevron-up
                name: Up
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: up
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:gap-card
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                aspect_ratio: 1/1
                size: 75px
                icon: mdi:chevron-left
                name: Left
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: left
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                aspect_ratio: 1/1
                size: 75px
                icon: mdi:circle
                name: Select
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: select
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                aspect_ratio: 1/1
                size: 75px
                icon: mdi:chevron-right
                name: Right
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: right
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:gap-card
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                aspect_ratio: 1/1
                size: 75px
                icon: mdi:chevron-down
                name: Down
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: down
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:gap-card
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:play-pause
                name: Play/Pause
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: play_pause
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:skip-backward
                name: Skip Backward
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: skip_backward
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:volume-plus
                name: Volume Up
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: volumeup
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:volume-mute
                name: Mute
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: mute
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:skip-forward
                name: Skip Forward
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: skip_forward
                    device: television
                  target:
                    entity_id: remote.livingroom
              - type: custom:button-card
                color: var(--paper-item-icon-color)
                icon: mdi:volume-minus
                name: Volume Down
                show_icon: true
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  data:
                    command: volumedown
                    device: television
                  target:
                    entity_id: remote.livingroom
    hold_action:
      action: call-service
      service: honeycomb
      service_data:
        autoclose: false
        buttons:
          - label: Other
            show_label: false
            tap_action:
              action: more-info
            icon: mdi:information
type: horizontal-stack
```

**Comment by Sian-Lee-SA** [comment]
Could you just download the [honeycomb-menu.js](https://github.com/Sian-Lee-SA/honeycomb-menu/blob/master/honeycomb-menu.js) and overwrite the one in your installation then hard reset/clear cache then test because technically the changes made recently should had already resolved this another issue needed the xy_pad to be serialised so Custom Button Card would ignore it.

**Comment by FedgarLurch** [comment]
Okay, I downloaded the version you sent, but no dice. Same issues.

**Comment by Sian-Lee-SA** [comment]
Ok so I have made a few changes and hopefully next release and future releases will go in the right direction... 
base on this

```yaml
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: call-service
  service: honeycomb
  service_data:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "[[[ return {{ x_percentage }} / 10; ]]]"
```

it is now going to be

```yaml
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: fire-dom-event
  honeycomb_menu:
    entity: entity
    xy_pad:
      on_release: true
      y:
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "HCJS: return Math.round(variables.y_percentage / 10);"
```

I also noticed you used x_percentage for a y field which would also cause errors if you have no x data. There is 2 changes to take note. Firstly we are now using fire-dom-event as the action instead of service-call. secondly, we are using the xy_pad variables as JS data inside variables. This all should cause no more conflicts with any 3rd party extentions.

Please download the latest js (like before) and test with updated config.

**Comment by FedgarLurch** [comment]
Okay, I got the latest, I tried what you posted, but I got no response. Nothing in the console, and no response from the buttons. 

When I changed to a `type: button` I did get this error, but nothing else

```
card-mod.js?hacstag=190927524343:1 Card-mod r: At path: tap_action.action -- Expected one of `"none","toggle","more-info","call-service","perform-action","url","navigate","assist"`, but received: "fire-dom-event"
    at y (https://redacted.website.domain/frontend_latest/66419.ZexNGgQFfa0.js:1:2782)
    at l (https://redacted.website.domain/frontend_latest/66419.ZexNGgQFfa0.js:1:2590)
    at F.value (https://redacted.website.domain/frontend_latest/38210.E7gqPRbN8hk.js:1:907)
    at F.value (https://redacted.website.domain/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343:1:60079)
    at F.i (https://redacted.website.domain/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343:1:53173)
    at t.setConfig (https://redacted.website.domain/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866245:215:1564)
    at i.value (https://redacted.website.domain/frontend_latest/611.bvewmeW5Ikk.js:5:31472)
```

And I checked, my other buttons seem to work. 
I rebooted and refreshed, and checked another device just to make sure everything was cleared out.

I did noticed that I forgot to change the y to an x a couple of times when I was troubleshooting, so that probably made this more of a pain in the ass to test. Ill go through and fix my comments so no one grabs my code by mistake.

**Comment by ngocjohn** [comment]
hi @Sian-Lee-SA, I can confirm that the js template for xy_pad for custom:button-card works, so for the default lovelace card. But for buttons items actions throws errors #75 in both yaml and ui. 

```
  - type: 'custom:button-card'
    entity: light.entrance_color_white_lights
    show_state: true
    tap_action:
      action: fire-dom-event
      honeycomb_menu:
        entity: light.entrance_color_white_lights
        xy_pad:
          on_release: false
          y:
            invert: false
            action: call-service
            service: light.turn_on
            service_data:
              # We can define another entity like normal
              entity_id: light.entrance_color_white_lights
              brightness_pct: 'HCJS: return Math.abs(variables.y_percentage);'
        buttons:
          - icon: 'mdi:information-variant'
            tap_action: more-info
          - icon: 'mdi:lightbulb'
            active: true
            tap_action:
              action: toggle
              entity_id: entity

  - type: button
    entity: light.entrance_color_white_lights
    name: Entrance
    icon: mdi:lightbulb
    tap_action:
      action: fire-dom-event
      honeycomb_menu:
        entity: light.entrance_color_white_lights
        xy_pad:
          on_release: false
          y:
            invert: false
            action: call-service
            service: light.turn_on
            service_data:
              # We can define another entity like normal
              entity_id: light.entrance_color_white_lights
              brightness_pct: 'HCJS: return Math.abs(variables.y_percentage);'
        buttons:
          - icon: 'mdi:information-variant'
            tap_action: more-info
          - icon: 'mdi:lightbulb'
            active: true
            tap_action:
              action: toggle
              entity_id: entity
```

**Comment by Sian-Lee-SA** [comment]
> Okay, I got the latest, I tried what you posted, but I got no response. Nothing in the console, and no response from the buttons.
> 
> When I changed to a `type: button` I did get this error, but nothing else
> 
> ```
> card-mod.js?hacstag=190927524343:1 Card-mod r: At path: tap_action.action -- Expected one of `"none","toggle","more-info","call-service","perform-action","url","navigate","assist"`, but received: "fire-dom-event"
>     at y (https://redacted.website.domain/frontend_latest/66419.ZexNGgQFfa0.js:1:2782)
>     at l (https://redacted.website.domain/frontend_latest/66419.ZexNGgQFfa0.js:1:2590)
>     at F.value (https://redacted.website.domain/frontend_latest/38210.E7gqPRbN8hk.js:1:907)
>     at F.value (https://redacted.website.domain/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343:1:60079)
>     at F.i (https://redacted.website.domain/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524343:1:53173)
>     at t.setConfig (https://redacted.website.domain/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866245:215:1564)
>     at i.value (https://redacted.website.domain/frontend_latest/611.bvewmeW5Ikk.js:5:31472)
> ```
> 
> And I checked, my other buttons seem to work. I rebooted and refreshed, and checked another device just to make sure everything was cleared out.
> 
> I did noticed that I forgot to change the y to an x a couple of times when I was troubleshooting, so that probably made this more of a pain in the ass to test. Ill go through and fix my comments so no one grabs my code by mistake.

Have you got the latest card_mod installed? that seems to be throwing that error. I literally just tested the following and is working
```yaml
      - type: button
        entity: light.kitchen_main
        tap_action:
          action: fire-dom-event
          honeycomb_menu:
            template: base
            xy_pad:
              on_release: true
              y:
                action: call-service
                invert: true
                service: cover.set_cover_position
                service_data:
                  entity_id: cover.window_2_shade_cover
                  position: "HCJS: return Math.round(variables.y_percentage);"
            buttons:
              - entity: climate.living_room
                icon: 'mdi:information-variant'
                tap_action:
                  action: more-info
              - entity: fan.living_room
                tap_action:
                  action: fire-dom-event
                  honeycomb_menu:
                    template: base
                    buttons:
                      - entity: camera.rtsp_front_yard
                        tap_action:
                          action: more-info
                      - entity: camera.rtsp_front_door
                        tap_action:
                          action: more-info
```

While i ain't using a enitity for cover, I am watching the data through WS

**Comment by Sian-Lee-SA** [comment]
@ngocjohn I just tested button actions and working fine. You also don't need entity_id: entity as its redundant.

**Comment by ngocjohn** [comment]
@Sian-Lee-SA Yes, they work, they just started throwing an error with loggin-mixin after the action. Which used to appear only in UI mode, now also in yaml mode. this issue #75

**Comment by Sian-Lee-SA** [comment]
Ok, you need to stick to that thread as it is not on topic for this. That "error" which I still can't reproduce is a seperate issue as you hsve point out via the link. Throwing in other issues from other threads just convolutes the issue of the current thread and makes things more confusing.

**Comment by FedgarLurch** [comment]
Okay, so I deleted every copy, plus rebooted both HA and my computer, removed the pointer in the resources, and finally, it seems to be working.

For anyone who wants to see my configuration: 

```
show_name: false
show_icon: true
type: custom:button-card
entity: cover.window_2_shade_cover
icon: mdi:curtains
show_state: false
tap_action:
  action: fire-dom-event
  honeycomb_menu:
    entity: entity
    xy_pad:
      on_release: true
      "y":
        action: call-service
        invert: true
        service: cover.set_cover_position
        service_data:
          entity_id: cover.window_2_shade_cover
          position: "HCJS: return 100 - (( variables.y_percentage + 100) / 200) * 100;"
```
The math here is because the position won't take negative numbers, so this makes the center 50% and full up / full down be 100% and 0% respectively.
