### ISSUE TITLE
Problem with nested honeycomb menu

### ISSUE THREAD

**Issue by Scarpetta3** [Sian-Lee-SA/honeycomb-menu#79]
Hello,
I worked on my code to modify it according the updates in the 1.4.x releases.
Everything works fine except for a nested honeycomb menu that doesn't seem to incorporate the correct parameters of the variables (particularly the "y" one).

The code snippet shown below if included in a simple (non-nested) honeycomb menu works correctly, while in a nested one it always provides the output value zero (so for the logic of the "if" variable.y always > 0).

```
xy_pad:
  on_release: true
  y:
    service: cover.set_cover_position
    data:
      entity_id: cover.tapparella_camera_singola
      position: 'HCJS: if (variables.y < 0) {return 100;} else {return 0;}'
```

Can you please look at this and see if you find a problem or not?

Thank You in advance

Regards
Matteo
