### ISSUE TITLE
Issue hiding buttons

### ISSUE THREAD

**Issue by nirnachmani** [Sian-Lee-SA/honeycomb-menu#87]
Sorry to bother. I am sure I am missing something simple but I just can't figure it out. I am trying to create a honeycomb menu with just two buttons and I can't figure out how to get rid of the unused buttons. I read the documentation and it seems to me that I need to use skip or break on the buttons I don't want, but I don't know how to. I tried to use show: false but I am still getting a semi-transparent button. I thought it might be my theme but changing to the default theme doesn't change the behavior.

This is the code I have now, inside a picture-elements card:

```             
- type: image
  entity: cover.study_blind
  style:
    top: 87%
    left: 51%
    transform: translate(-50%, -50%) var(--study-blind-scale)
    z-index: 10
    opacity: 0
    user-select: none
    transition: none
  image: /local/buttons/button.webp
  tap_action:
    action: fire-dom-event
    honeycomb_menu:
      entity: cover.study_blind
      size: 225
      spacing: 0
      buttons:
        - icon: mdi:arrow-up-bold-circle
          tap_action:
            action: call-service
            service: cover.open_cover
            service_data:
              entity_id: cover.study_blind
        - icon: mdi:arrow-down-bold-circle
          tap_action:
            action: call-service
            service: cover.close_cover
            service_data:
              entity_id: cover.study_blind
        - show: false
        - skip: 
        - break: 
        - type: null
```                  

This is what I am getting:

![Image](https://github.com/user-attachments/assets/b7144dca-8720-42d8-83a2-d23d733c0ebf)

What am I missing?

**Comment by Sian-Lee-SA** [comment]
you dont put `:` at then end, you are turning it into an object and not a string. Just write `- skip`

**Comment by nirnachmani** [comment]
Thanks. I tried that as well but I am still getting a semi-transparent honeycomb: 

```
                honeycomb_menu:
                  entity: lock.gym_door
                  size: 225
                  spacing: 0
                  animation_speed: 25
                  buttons:
                    - break
                    - skip
                    - icon: mdi:lock-open
                      color_type: icon
                      color: "#4a6880"
                      tap_action:
                        action: call-service
                        service: lock.unlock
                        service_data:
                          entity_id: lock.gym_door
                    - icon: mid:void
                    - icon: mid:void
                    - icon: mdi:lock
                      color_type: icon
                      color: "#4a6880"
                      tap_action:
                        action: call-service
                        service: lock.lock
                        service_data:
                          entity_id: lock.gym_door
```

Gives me:

![Image](https://github.com/user-attachments/assets/733248b3-a679-4f16-bf52-7fe17bea9dd3)

I wonder if it is something to do with my theme. I managed to overcome this  by using 'icon: mid:void' as in my example above.
