### ISSUE TITLE
HoneyComb menu will not work with floorplan for multiple entities

### ISSUE THREAD

**Issue by wambs** [Sian-Lee-SA/honeycomb-menu#92]
I’m using the Honeycomb menu in a custom:floorplan-card. Recently it stopped working because the depreciated service call was removed.
So, I updated my yaml but its still not working. Based on docs I had to change the service call to a fire-dom-event. However, when I do, it still does not work.

Below is a sample of the Yaml and the error message.

Error in the logs:
Uncaught error from Chrome 135.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading ‘addEventListener’) zt.close (/hacsfiles/honeycomb-menu/honeycomb-menu.js:257:973) /hacsfiles/honeycomb-menu/honeycomb-menu.js:119:3195 window.honeycomb_menu (/hacsfiles/honeycomb-menu/honeycomb-menu.js:119:3901) HTMLBodyElement. (/hacsfiles/honeycomb-menu/honeycomb-menu.js:119:4110) pe (/hacsfiles/ha-floorplan/floorplan.js:52:482) Pi.handleActions (/hacsfiles/ha-floorplan/floorplan.js:131:19122) me.onClick (/hacsfiles/ha-floorplan/floorplan.js:131:17855) /hacsfiles/ha-floorplan/floorplan.js:52:3424

          ```
     - entities:
        - fan.master_bed_room_fan
        - fan.south_bed_room_fan
        - fan.north_bed_room_fan
       tap_action:
          action: fire-dom-event
          honeycomb_menu:
            buttons:
              - icon: mdi:information-variant
                tap_action:
                  action: more-info
              - icon: mdi:fan-off
                active: '[[[ return entity.attributes.speed == "off" ]]]'
                tap_action:
                  action: call-service
                  service: fan.set_preset_mode
                  data:
                    entity_id: entity
                    preset_mode: "off"
              - icon: mdi:fan-speed-1
                active: '[[[ return entity.attributes.speed == "slow" ]]]'
                tap_action:
                  action: call-service
                  service: fan.set_preset_mode
                  data:
                    entity_id: entity
                    preset_mode: slow
        state_action:
          action: call-service
          service: floorplan.class_set
          service_data:
            class: >-
              ${(entity.state === "on") ? "fan-" +
              entity.attributes.preset_mode : ""}
  ```

**Comment by Sian-Lee-SA** [comment]
Try replacing eg `[[[ return entity.attributes.speed == "slow" ]]]` to `HCJS: return entity.attributes.speed == "slow"` and other similar code. Also check console logs and always hard refresh.

**Comment by Nipal33** [comment]
Hello,

I have the exact same problem in my floorplan. I managed to switch to fire-dom when the entity is hardcoded but as soon as I have to use a variable it doesn't work anymore.
I have tried the 3 ways I know of:
  - ${element.id.replace('xxx', 'yyy')}
 - '[[[ return entity.entity_id; ]]]'
 - 'HCJS! return entity.entity_id;'

None of them seems to work in the honeycomb fire-dom while they where all working with the service before.

I also tried to go through a template but I can't make it work from floorplan elements/entities. It actually works from custom button added on top of the floorplan (i.e. I can use variable and JS in the custom_button template with Honeycomb) but not with the floorplan elements.

**Comment by wambs** [comment]
This is still an issue reported by multiple users. Is there a plan to fix this? I can provide help with testing.
Closing an issue because the code owners have not had time to investigate/fix issue is not a good process.

**Comment by Sian-Lee-SA** [comment]
This is because floorplan doesn't pass in the entity to fire-dom-event and doesn't understand  that honeycomb has a field that can define the entity. You will need to manually define each entity for the menu eg... 

```yaml
entity: fan.north_bed_room_fan
tap_action:
    action: fire-dom-event
    honeycomb_menu:
      entity: fan.north_bed_room_fan
      buttons:
        ...
```

Alternatively you can invoke it using floorplan execute action and call `window.honeycomb_menu()` while passing in the options as an object for the first arg which is a bit more involved but the entity variable should be available. Personally I use lovelace_gen to simplify repeating code.
